/*
@
 This file contains the types constants
@
*/

export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST ";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS ";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE ";

export const CLEAR_ARTICLES = "CLEAR_ARTICLES";

export const REQUEST_LIKE_ARTICLE = "REQUEST_LIKE_ARTICLE";
export const SUCCESS_LIKE_ARTICLE = "SUCCESS_LIKE_ARTICLE";
export const FAILURE_LIKE_ARTICLE = "FAILURE_LIKE_ARTICLE";

export const REQUEST_REMOVE_LIKE_ARTICLE = "REQUEST_REMOVE_LIKE_ARTICLE";
export const SUCCESS_REMOVE_LIKE_ARTICLE = "SUCCESS_REMOVE_LIKE_ARTICLE";
export const FAILURE_REMOVE_LIKE_ARTICLE = "FAILURE_REMOVE_LIKE_ARTICLE";
