/*
@
 This file contains the types constants
@
*/

export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST ";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS ";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE ";

export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST ";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS ";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE ";

export const REQUEST_LIKE_QUESTION = "REQUEST_LIKE_QUESTION ";
export const SUCCESS_LIKE_QUESTION = "SUCCESS_LIKE_QUESTION ";
export const FAILURE_LIKE_QUESTION = "FAILURE_LIKE_QUESTION ";

export const REQUEST_REMOVE_LIKE_QUESTION = "REQUEST_REMOVE_LIKE_QUESTION ";
export const SUCCESS_REMOVE_LIKE_QUESTION = "SUCCESS_REMOVE_LIKE_QUESTION ";
export const FAILURE_REMOVE_LIKE_QUESTION = "FAILURE_REMOVE_LIKE_QUESTION ";

export const CLEAR_QUESTIONS = "CLEAR_QUESTIONS";

