/*
@
 This file contains the types constants
@
*/

export const FETCH_DISCUSSIONS_REQUEST = "FETCH_DISCUSSIONS_REQUEST ";
export const FETCH_DISCUSSIONS_SUCCESS = "FETCH_DISCUSSIONS_SUCCESS ";
export const FETCH_DISCUSSIONS_FAILURE = "FETCH_DISCUSSIONS_FAILURE ";

export const DELETE_DISCUSSIONS_REQUEST = "DELETE_DISCUSSIONS_REQUEST ";
export const DELETE_DISCUSSIONS_SUCCESS = "DELETE_DISCUSSIONS_SUCCESS ";
export const DELETE_DISCUSSIONS_FAILURE = "DELETE_DISCUSSIONS_FAILURE ";

export const CHANGING_DISCUSSION_STATUS = "CHANGING_DISCUSSION_STATUS";

export const CLEAR_DISCUSSIONS = "CLEAR_DISCUSSIONS ";

export const NEW_DISSCUSSION_ADDED = "NEW_DISSCUSSION_ADDED ";

export const GET_OR_CREATE_DISCUSSION = "GET_OR_CREATE_DISCUSSION";
